// <auto-generated/>
namespace streaming_tools.Models {
    /// <summary>
    ///     The response from nullinside for the "code" url.
    /// </summary>
    public class NullInsideTwitchCodeResponseJson {
        /// <summary>
        ///     The URL to launch in the browser to get the "code" from.
        /// </summary>
        public string url { get; set; }
    }
}